### ISSUE TITLE
My grafana wont connect to mongoDB, can anybody help?

### ISSUE THREAD

**Issue by muhbianco** [ajeje93/grafana-mongodb-docker#2]
![image](https://user-images.githubusercontent.com/76020677/186781853-34be24a9-dad5-4b52-826f-583ba7a41533.png)

**Comment by ajeje93** [comment]
In the url field at the top you should put `http://localhost:3333` which is the port on which the NodeJS proxy server is running (https://github.com/JamesOsgood/mongodb-grafana#install-and-start-the-mongodb-proxy-server)

**Comment by muhbianco** [comment]
Thank u @ajeje93. It works!

But, one more problem to solve.... check this out

My aggregates wont work, returns something like "update your driver"

Logs show me that:
 [MONGODB DRIVER] Warning: Current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.
 
 im trying to edit the file mongo_client.js but my knowledge in node is terrible... and my english too (sry for that)


Can you help me?

**Comment by ajeje93** [comment]
Sorry, I don't know how to help you. Consider that the plugin is not maintained anymore by the creator. A guy made a new version of the plugin (https://github.com/JamesOsgood/mongodb-grafana/issues/123#issuecomment-1193218998), but I didn't try that yet.
