### ISSUE TITLE
Private repo

### ISSUE THREAD

**Issue by ffanccybear** [ajeje93/grafana-mongodb-docker#9]
I think they made their repo private
https://github.com/SiemaApplications/mongodb-grafana

**Comment by ajeje93** [comment]
Thank you for opening the issue! Searching on the original plugin repo I have discovered their new repo https://github.com/SiemaApplications-attic/mongodb-grafana.
I'll try to update everything in the next days

**Comment by ajeje93** [comment]
Done!
